openapi: 3.0.0
info:
  title: Coronatime API
  version: 1.0.0

servers:
  - url: http://localhost:4000/api
    description: local server
  - url: https://coronatime-api.devtest.ge/api
    description: production server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /countries:
    get:
      tags:
        - Countries and Statistics
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /register:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  required: true
                email:
                  type: string
                  required: true
                password:
                  type: string
                  required: true
                repeatPassword:
                  type: string
                  required: true
                redirectOnConfirm:
                  type: string
                  required: true
              example:
                username: gela
                email: gela@redberry.ge
                password: amilaxvari
                repeatPassword: amilaxvari
                redirectOnConfirm: https://coronatime.giuna.redberryinternship.ge/confirm-account
      responses:
        '201':
          description: Sucessfully registered
          content:
            application/json:
              schema:
  /login:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  required: true
                password:
                  type: string
                  required: true
            example:
              username: gela
              password: amilaxvari
      responses:
        '200':
          content:
            application/json:
              example:
                token: some-token
  /confirm-account:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                hash:
                  type: string
                  required: true
            example:
              hash: 6283b36ccb785c87b46ee64f
      responses:
        '200':
          description: Successfully confirmed user account
          content:
            application/json:
              schema:
  /password/send-recovery-link:
    post:
      tags:
        - Password Recovery
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  required: true
                backlink:
                  type: string
                  required:
                  description: URL on which user will be redirected from email link
            example:
              email: gela@redberry.ge
              backlink: https://coronatime.giuna.redberryinternship.ge/password-recovery
      responses:
        '200':
          description: mail sent successfully
          content:
            application/json:
              example:
                message: password recovery mail sent successfully
  /password/recover:
    post:
      tags:
        - Password Recovery
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                hash:
                  type: string
                  required: true
                password:
                  type: string
                  required: true
                repeatPassword:
                  type: string
                  required: true
            example:
              hash: 6283b36ccb785c87b46ee64f
              password: amilaxvari
              repeatPassword: amilaxvari

      responses:
        '200':
          description: Successfully recovered password
          content:
            application/json:
              schema:


